"""Developer tools for the SDK."""

import abc
import ast
import subprocess
from pathlib import Path
from typing import Annotated, ClassVar, NamedTuple

import typer
from jinja2 import Environment, PackageLoader, Template

from ..logging_config import get_console, get_logger
from .core import ProjectContext  # noqa: TC001

logger = get_logger(__name__)
app = typer.Typer(help="Developer tools for audiobookshelf-sdk.")
console = get_console()

# Point to the parent abs_sdk package
PACKAGE_ROOT = Path(__file__).resolve().parent.parent
RESPONSE_ROOT = PACKAGE_ROOT / "response"
RESPONSE_INIT_FILE = RESPONSE_ROOT / "__init__.py"

jinja_env = Environment(loader=PackageLoader(PACKAGE_ROOT.stem, package_path="devtools_templates"))


class FileTemplate(abc.ABC):
    """Abstract base class for file templates, defining the interface for generating file content."""

    TEMPLATE: ClassVar[str]

    def get_template(self) -> Template:
        """Load the Jinja2 template for this file type."""
        return jinja_env.get_template(self.TEMPLATE)

    def generate_content(self) -> str:
        """Generate the content for the file by rendering the template with appropriate context."""
        template = self.get_template()
        return template.render(package_root=PACKAGE_ROOT.stem)


class InitFile(FileTemplate):
    """Marker dataclass for __init__.py files, allowing for potential future metadata or methods related to package initialization."""

    TEMPLATE: ClassVar[str] = "__init__.py.j2"


class ModuleFile(FileTemplate):
    """A module file to be created, encapsulating the content generation logic."""

    TEMPLATE: ClassVar[str] = "module.py.j2"


def _response_module_files() -> list[Path]:
    return sorted(
        file_path
        for file_path in RESPONSE_ROOT.glob("*.py")
        if file_path.name not in {"__init__.py"}
    )


def _public_class_names(module_path: Path) -> list[str]:
    parsed = ast.parse(module_path.read_text(encoding="utf-8"), filename=str(module_path))
    return sorted(
        class_node.name
        for class_node in parsed.body
        if isinstance(class_node, ast.ClassDef) and not class_node.name.startswith("_")
    )


class _ResponseClassInfo(NamedTuple):
    init_content: str
    module_count: int
    class_count: int


def _build_response_init_content() -> _ResponseClassInfo:
    imports: list[str] = []
    all_names: list[str] = []

    for module_path in _response_module_files():
        module_name = module_path.stem
        class_names = _public_class_names(module_path)
        if not class_names:
            continue

        all_names.extend(class_names)

        if len(class_names) == 1:
            imports.append(f"from .{module_name} import {class_names[0]}")
            continue

        import_lines = [f"from .{module_name} import ("]
        import_lines.extend(f"    {class_name}," for class_name in class_names)
        import_lines.append(")")
        imports.append("\n".join(import_lines))

    all_names = sorted(all_names)

    first_line = (
        '"""Auto-generated by abs_sdk.cli.devtools.build_response_init. Do not edit manually."""'
    )

    lines: list[str] = [first_line, ""]
    if imports:
        lines.extend(imports)
        lines.append("")

    lines.append("__all__ = [")
    lines.extend(f'    "{class_name}",' for class_name in all_names)
    lines.append("]")
    lines.append("")

    return _ResponseClassInfo(
        init_content="\n".join(lines), module_count=len(imports), class_count=len(all_names)
    )


def normalize_target(module_path: str, package: bool = False) -> Path:
    """Convert a dotted module path or filesystem path into an absolute Path within the package.

    Args:
        module_path: The input module path, either in dotted form (e.g., "reports.new.module") or as a filesystem path (e.g., "reports/new/module.py").
        package: If True, ensures the target is treated as a package (i.e., ends with __init__.py).

    Returns:
        An absolute Path object pointing to the target module file within the package.
    """
    module_path = module_path.strip()
    if package and module_path.lower().endswith(".py"):
        raise typer.BadParameter(
            "Cannot specify a .py file when creating a package. Use a dotted path without .py extension."
        )
    module_path = module_path.strip().rstrip(".py")
    path = Path(module_path.replace(".", "/"))
    if package and not path.name.endswith("__init__"):
        path /= "__init__.py"
    path = path.with_suffix(".py")
    return path if path.is_absolute() else PACKAGE_ROOT / path


def _ensure_package_inits(target: Path, *, dry_run: bool = False) -> None:
    relative_parts = target.relative_to(PACKAGE_ROOT).parts[:-1]
    current = PACKAGE_ROOT
    for part in relative_parts:
        current /= part
        if not dry_run:
            current.mkdir(parents=True, exist_ok=True)
            init_file = current / "__init__.py"
            if not init_file.exists():
                _ = init_file.write_text(InitFile().generate_content(), encoding="utf-8")
        else:
            console.log(f"[yellow]Would create directory: {current}[/yellow]")
            console.log(f"[yellow]Would create __init__.py at: {current / '__init__.py'}[/yellow]")


def _write_module(target: Path, force: bool, *, dry_run: bool = False) -> None:
    if not dry_run:
        target.parent.mkdir(parents=True, exist_ok=True)
    if target.name == "__init__.py":
        return
    if target.exists() and not force:
        raise typer.BadParameter(f"Module already exists: {target}. Use --force to overwrite.")

    if not dry_run:
        _ = target.write_text(ModuleFile().generate_content(), encoding="utf-8")
    else:
        console.log(f"[yellow]Would write module file at: {target}[/yellow]")


@app.command("create-module")
def create_module(
    ctx: ProjectContext,
    module_path: str,
    package: Annotated[
        bool, typer.Option("-p", "--package", help="Create as a package (with __init__.py)")
    ] = False,
    force: Annotated[
        bool, typer.Option("-f", "--force", help="Overwrite existing module if it exists")
    ] = False,
) -> None:
    """Create a new Python module with default logger setup.

    The path may be provided as a dotted path (e.g., "reports.new.module") or a
    filesystem path (e.g., "reports/new/module.py"). All parent packages and
    __init__.py files are created as needed.
    """
    context = ctx.obj
    _dry_run = context.dry_run

    if _dry_run:
        console.log(
            "[yellow]Dry run mode enabled. The following actions would be performed:[/yellow]"
        )

    with console.status("[bold magenta]Creating module...", spinner="dots") as _status:
        target = normalize_target(module_path, package=package)
        console.log(f"[bold green]Normalized module path to: [/bold green][u cyan]{target}[/]")
        try:
            _relative_path = target.relative_to(PACKAGE_ROOT)
        except ValueError as exc:
            raise typer.BadParameter(
                f"Module path must stay within package root: {PACKAGE_ROOT}"
            ) from exc

        _ensure_package_inits(target, dry_run=_dry_run)
        console.log(
            f"[bold green]Ensured package __init__.py files up to [/bold green][u cyan]{target.parent}[/]"
        )
        _write_module(target, force=force, dry_run=_dry_run)
        console.log(f"[bold green]Wrote module file at [/bold green][u repr.filename]{target}[/]")

    console.rule("[bold green]Module created successfully![/bold green]")


@app.command("shell")
def shell(
    module: Annotated[
        str | None,
        typer.Option(
            "-m",
            "--module",
            help="Optional dotted path to import into the shell (e.g., weldon.weldon)",
        ),
    ] = None,
    color: Annotated[
        bool,
        typer.Option("--no-color", help="Disable rich-colored terminal output"),
    ] = True,
) -> None:
    """Start a colored IPython shell with optional module preloaded.

    - Uses Rich console for styled output
    - Imports the given module and binds it to `mod`
    - Also exposes `console` and `logger` in the shell namespace
    """
    from importlib import import_module

    ns: dict[str, object] = {"console": console, "logger": logger}
    banner = "[bold green]WeldonPackage Dev Shell[/bold green]"

    if module:
        try:
            loaded = import_module(module)
            ns["mod"] = loaded
            ns["dt"] = import_module("datetime")
            banner += f"\nImported: [cyan]{module}[/cyan] as [yellow]mod[/yellow]"
            banner += "\nImported: [cyan]datetime[/cyan] as [yellow]dt[/yellow]"
        except Exception as exc:  # noqa: BLE001
            logger.error("Failed to import module %s: %s", module, exc)
            banner += f"\n[red]Failed to import {module}: {exc}[/red]"

    # Prefer IPython for colors and better UX; fallback to code.InteractiveConsole
    try:
        from IPython.terminal.interactiveshell import TerminalInteractiveShell
        from traitlets.config import Config

        c = Config()
        c.TerminalInteractiveShell.colors = "Linux" if color else "NoColor"  # pyright: ignore[reportAny]
        c.TerminalInteractiveShell.confirm_exit = False  # pyright: ignore[reportAny]
        c.TerminalInteractiveShell.display_page = False  # pyright: ignore[reportAny]

        console.print(banner)
        sh = TerminalInteractiveShell.instance(config=c)
        sh.user_ns.update(ns)  # pyright: ignore[reportUnknownMemberType]
        sh.mainloop()
    except Exception:  # noqa: BLE001
        logger.warning("IPython not available, falling back to standard shell.", exc_info=True)
        import code

        console.print(banner)
        code.interact(local=ns)


@app.command("build-response-init")
def build_response_init(
    ctx: ProjectContext,
    skip_formatting: Annotated[
        bool,
        typer.Option("--skip-formatting", help="Skip post-write formatting with Ruff"),
    ] = False,
) -> None:
    """Build response/__init__.py from all top-level public response classes."""
    context = ctx.obj
    _dry_run = context.dry_run

    with console.status("[bold magenta]Building response __init__.py...", spinner="dots"):
        if not RESPONSE_ROOT.exists():
            raise typer.BadParameter(f"Response package not found: {RESPONSE_ROOT}")

        response_class_info = _build_response_init_content()
        init_content = response_class_info.init_content
        module_count = response_class_info.module_count
        class_count = response_class_info.class_count

        if _dry_run:
            console.log(
                "[yellow]Dry run mode enabled. The following file would be written:[/yellow]"
            )
            console.log(f"[u cyan]{RESPONSE_INIT_FILE}[/]")
            console.log(
                f"[yellow]Would include {class_count} public classes from {module_count} response modules.[/yellow]"
            )
            return

        _ = RESPONSE_INIT_FILE.write_text(init_content, encoding="utf-8")
        if not skip_formatting:
            try:
                _ = subprocess.run(
                    [
                        "ruff",
                        "check",
                        "--fix",
                        "--select",
                        "I001,RUF022",
                        str(RESPONSE_INIT_FILE),
                    ],
                    check=True,
                    capture_output=True,
                    text=True,
                )
            except FileNotFoundError:
                console.log(
                    "[yellow]Ruff is not available on PATH; skipping post-write formatting.[/yellow]"
                )
            except subprocess.CalledProcessError as exc:
                console.log(
                    "[yellow]Ruff formatting encountered issues; keeping generated file. Exit code: {exc.returncode}[/yellow]"
                )
                if exc.stderr:  # pyright: ignore[reportAny]
                    console.log(f"[yellow]{exc.stderr.strip()}[/yellow]")  # pyright: ignore[reportAny]

    console.rule("[bold green]response/__init__.py built successfully![/bold green]")
    console.log(
        f"[bold green]Included {class_count} public classes from {module_count} response modules.[/bold green]"
    )


if __name__ == "__main__":
    app()
